export const btrQuests = [
  { id: 'btr_1', title: 'Рука помощи', x: 0, y: 0, parentId: null, kappa: false },
  { id: 'btr_2', title: 'Задержка отправления. Часть 1', x: 0, y: 180, parentId: 'btr_1', kappa: false },
  { id: 'btr_3', title: 'Задержка отправления. Часть 2', x: 0, y: 360, parentId: 'btr_2', kappa: false },
  { id: 'btr_4', title: 'Шиномонтажка', x: 0, y: 540, parentId: 'btr_3', kappa: false },
  { id: 'btr_5', title: 'Скорая расплата', x: 0, y: 720, parentId: 'btr_4', kappa: false },
  { id: 'btr_6', title: 'Навести мосты', x: 0, y: 900, parentId: 'btr_5', kappa: false },
  { id: 'btr_7', title: 'Натуральный обмен', x: 0, y: 1080, parentId: 'btr_6', kappa: false },
  { id: 'btr_8', title: 'Скрепить дружбу', x: 0, y: 1260, parentId: 'btr_7', kappa: false },
  { id: 'btr_9', title: 'Недосдача', x: -300, y: 1440, parentId: 'btr_8', kappa: false },
  { id: 'btr_10', title: 'Палки в колёса', x: -150, y: 1440, parentId: 'btr_8', kappa: false },
  { id: 'btr_11', title: 'Поменять батарейку', x: 0, y: 1440, parentId: 'btr_8', kappa: false },
  { id: 'btr_12', title: 'Закрыть небо', x: 150, y: 1440, parentId: 'btr_8', kappa: false },
  { id: 'btr_13', title: 'Переиграть и уничтожить', x: 300, y: 1440, parentId: 'btr_8', kappa: false },
  { id: 'btr_14', title: 'Цена независимости', x: 250, y: 1620, parentId: 'btr_13', kappa: false },
  { id: 'btr_15', title: 'Выбирай друзей правильно', x: 400, y: 1620, parentId: 'btr_13', kappa: false },
  { id: 'btr_16', title: 'Задержка поставки', x: -400, y: 1260, parentId: 'btr_7', kappa: false },
  { id: 'btr_17', title: 'Спросить дорогу', x: -500, y: 1440, parentId: 'btr_16', kappa: false },
  { id: 'btr_18', title: 'Стабилизировать бизнес', x: -350, y: 1440, parentId: 'btr_16', kappa: false },
  { id: 'btr_19', title: 'Шиномонтажка. Вторая попытка', x: 500, y: 720, parentId: 'btr_3', kappa: false },
  { id: 'btr_20', title: 'Заказ со стороны', x: 400, y: 900, parentId: 'btr_19', kappa: false },
  { id: 'btr_21', title: 'Неизбежный ответ', x: 600, y: 900, parentId: 'btr_19', kappa: false },
  { id: 'btr_22', title: 'Выше головы', x: 600, y: 1080, parentId: 'btr_21', kappa: false },
  { id: 'btr_23', title: 'Отклонение от маршрута', x: 450, y: 1260, parentId: 'btr_22', kappa: false },
  { id: 'btr_24', title: 'Подстелить соломку', x: 550, y: 1260, parentId: 'btr_22', kappa: false },
  { id: 'btr_25', title: 'Ключевой партнёр', x: 650, y: 1260, parentId: 'btr_22', kappa: false },
  { id: 'btr_26', title: 'Убойный аргумент', x: 750, y: 1260, parentId: 'btr_22', kappa: false },
  { id: 'btr_27', title: 'Непыльная подработка', x: 200, y: 720, parentId: 'btr_3', kappa: false },
];